language: python
cache: pip
python:
- 3.6
- 3.7
install:
- pip install flake8 pytest pyopenssl
before_install:
- pip install --upgrade pip setuptools wheel
- pip install --only-binary=numpy,pandas numpy pandas
- sudo apt-get install build-essential python-dev libxml2 libxml2-dev zlib1g-dev
- pip install python-igraph
- if [[ $TRAVIS_PYTHON_VERSION == 2.7.13 ]]; then pip install IPython==5.0; fi
- python setup.py install
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
before_script:
- time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
- time flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
